16 create watch2gather api for chatbot
maier-s/LaSaga-Discord-Bot pull request #17
Opened 2022-01-23 22:56 UTC by maier-s

Added W2G functionallity.

Create and Update room

2022-01-23 23:48 UTC, maier-s commented
Code is now ready for merge

2022-01-25 12:44 UTC, d-strobel requested changes
Code is fine. 
The ".DS_Store" file should not be in version control since it is a macOS specific file for folder previews. Please add it to gitignore.

2022-01-25 19:28 UTC, maier-s commented
@d-strobel done change. Please merge

2022-01-25 21:54 UTC, d-strobel approved these changes

2022-01-25 21:55 UTC, merged